{
 "title": "Ingress Dashboard",
 "description": "Jesse's first attempt",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(container_memory_working_set_bytes,namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Ingress 403 in Prod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(status, exported_service) (increase(nginx_ingress_controller_requests{status=\"403\", exported_namespace=~\"$namespace\"}[1h]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Ingress Usage in Prod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(status, exported_service) (increase(nginx_ingress_controller_requests{status=\"200\", exported_namespace=~\"kubecost-faefacd2-1|$namespace\"}[1h]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Ingress Errors in Prod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(status, exported_service) (increase(nginx_ingress_controller_requests{status!=\"200\", exported_namespace=~\"$namespace\"}[1h]))",
     "legendFormat": "{{status}}"
    }
   ]
  }
 ]
}