apiVersion: batch/v1
kind: CronJob
metadata:
  name: startup-spike-job-2m
spec:
  schedule: "46 * * * *"  # Run every hour, adjust as needed
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: startup-spike-2m
            image: gcr.io/guestbook-227502/qa-stress:0.0.1
            command: ["/bin/bash"]
            args: ["/scripts/startup-spike.sh"]
            volumeMounts:
            - name: startup-spike-script
              mountPath: /scripts
            resources:
              limits:
                cpu: 100m
                memory: 100Mi
              requests:
                cpu: 100m
                memory: 100Mi
            securityContext:
              runAsNonRoot: false
              allowPrivilegeEscalation: false
              seccompProfile:
                type: RuntimeDefault
              capabilities:
                drop: ["ALL"]
          volumes:
          - name: startup-spike-script
            configMap:
              name: startup-spike-2m
              defaultMode: 0755

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: startup-spike-2m
data:
  startup-spike.sh: |-
    #!/bin/bash

    # Run stress-ng for 3 minutes using 5 CPUs
    stress-ng --cpu 1 --timeout 2m
    echo "Stress-ng completed"
    echo "Sleeping for 10 minutes"
    sleep 10m
